default: &default
 adapter: mysql2
 encoding: utf8
 pool: 5
 host: localhost
 username: root
 password: admin
 socket: /var/run/mysqld/mysqld.sock

development:
 <<: *default
 database: BookStore

test:
 <<: *default
 database: BookStore_test
